gen 8 multi for chinese server
CTCC1/Pokemon-Showdown pull request #42
Opened 2021-06-02 13:59 UTC by zerodragon123

2021-06-04 16:06 UTC, Starmys reviewed
小改一下再加个4p 1v1v1v1的OU，明天咱们测试一下天梯，再看看有没有别的bug，没问题的话周一就更新到国服

2021-06-04 16:06 UTC, Starmys commented on config/formats.ts
> +		name: "[Gen 8]multi(4p for doublesbaltte)",
如果想在选队时调出G8OU队伍库：```[Gen 8] OU (Multi)```或者直接```[Gen 8] OU (4p2v2)```
也可以保留成现在这样，但是新玩家没队伍可能会是个问题。或者再开一个分级，两边都要，OU 4p2v2供娱乐，现在这个供比赛。你按照自己的想法看看怎样比较合适吧

2021-06-04 16:06 UTC, Starmys commented on config/formats.ts
> +
再加一个一样的```[Gen 8] OU (Free-For-All)```或者```[Gen 8] OU (4p)```:
```
	{
		name: "[Gen 8] OU (4p)",
		desc: `4P 1v1v1v1 OU`,
		mod: 'gen8',
		tournamentShow: false,
		rated: true,
		gameType: 'freeforall',
		ruleset: ['OU'],
	},
```

2021-06-04 16:25 UTC, CTCC1 requested changes

2021-06-04 16:25 UTC, CTCC1 commented on config/formats.ts
> +		rated: true,
rated 建议保留false?

2021-06-04 16:25 UTC, CTCC1 commented on config/formats.ts
> +		name: "[Gen 8]multi(4p for doublesbaltte)",
(不是很重要) [Gen 8]后面空一格  后面文字按照其他分级的格式来写(每个单词首字母大写)，例如
[Gen 8] OU (Multi)    这个根据OU规则
[Gen 8] Doubles OU (Multi)  这个根据DOU规则

2021-06-07 08:14 UTC, Starmys requested changes

2021-06-07 08:14 UTC, Starmys commented on config/formats.ts
> +			this.add('html', '<em style="color:#445566;display:block;" >'+this.sides[2]?.pokemon[0].name + '/' + this.sides[2]?.pokemon[1].name + '/' + this.sides[2]?.pokemon[2].name + '/' + this.sides[2]?.po
这样如果p3p4带不满6只会报错， 建议改成：
```
this.sides[2]?.pokemon.map(x => x.name).join(' / ')
```

2021-06-07 14:47 UTC, merged